spring:
  application:
    name: kafka-stream
  kafka:
    streams:
      application-id: springboot-kafka-stream
    bootstrap-servers:
      - localhost:9092
    properties:
      default:
        key:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde


logging:
  level:
    root: info
  file:
    name: log/kafka-stream.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS, Australia/Sydney} %-5level  - %msg%n'
  logback:
    rollingpolicy:
      file-name-pattern: 'log/kafka-stream.log.%d{yyyy-MM-dd, Australia/Sydney}.%i.log'
      max-file-size: 1MB
      max-history: 60